name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: Wunderbyte-GmbH/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      codechecker_max_warnings: 0
      disable_phpcpd: true

