name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  ci:
    uses: Wunderbyte-GmbH/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      disable_release: true  # Use true if using the tag-based release workflow
      codechecker_max_warnings: 0
      enable_phpmd: true

      workarounds: |
        echo "MUSTACHE_IGNORE_NAMES=twtable_list_row.mustache,twtable_cards_row.mustache" >> $GITHUB_ENV
        # WORKAROUND 17/04/2025: The following code is a workaround for the "File is stale and needs to be rebuilt" error
        # This occurs when AMD modules import Moodle core dependencies
        # See issue: https://github.com/moodlehq/moodle-plugin-ci/issues/350
        # This workaround should be removed once the issue is fixed upstream
        # Load NVM and use the version from .nvmrc
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # Go to moodle directory
        cd moodle

        # Use NVM to set Node version and ensure grunt-cli is installed
        nvm use
        npm install
        npm install -g grunt-cli

        # Go back to plugin directory
        cd ../plugin

        # Pre-build AMD files to avoid stale file warnings
        echo "=== Building AMD files before CI check ==="
        grunt --gruntfile ../moodle/Gruntfile.js amd
        echo "AMD files built successfully"

        # Go Back to main directory
        cd ..
        # END OF WORKAROUND

    secrets:
      # Only needed if NOT using disable_release: true
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}